{{- if .Values.namespaces.create -}}
{{- range $tier := list "control" "load" "data" "infra" "sandbox" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ printf "%s-%s" $.Release.Name $tier }}
  labels:
    {{- include "velocity.commonLabels" $ | nindent 4 }}
    velocity.tier: {{ $tier }}
    {{- if eq $tier "sandbox" }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit:    restricted
    pod-security.kubernetes.io/warn:     restricted
    {{- else }}
    pod-security.kubernetes.io/enforce: {{ $.Values.global.podSecurityStandard }}
    {{- end }}
{{- end }}
{{- end }}
