#include "velocity/orderbook.h"

#include <algorithm>
#include <iterator>

// Simple deterministic matching: match against opposite side price levels in
// deterministic price-time order. Uses integer ticks for price and integer
// quantities. This is a baseline implementation for correctness validation.

namespace velocity {

std::vector<Trade> InstrumentOrderBook::ApplyOrder(const OrderPlacedEvent& ev) {
    std::vector<Trade> trades;

    InternalOrder incoming{
        .order_id = ev.order_id,
        .remaining_qty = ev.quantity,
        .price_ticks = ev.price_ticks,
        .arrival_seq = next_seq_++,
    };

    if (ev.is_buy) {
        // Match against asks: lowest price first
        auto it = asks_.begin();
        while (incoming.remaining_qty > 0 && it != asks_.end()) {
            int64_t level_price = it->first;
            if (level_price > incoming.price_ticks)
                break;  // no aggressive match
            auto& queue = it->second;
            while (!queue.empty() && incoming.remaining_qty > 0) {
                InternalOrder& maker = queue.front();
                int64_t qty = std::min(incoming.remaining_qty, maker.remaining_qty);
                // produce trade
                Trade t;
                t.trade_id = "";  // generated by higher layer if needed
                t.maker_order_id = maker.order_id;
                t.taker_order_id = incoming.order_id;
                t.price_ticks = maker.price_ticks;
                t.quantity = qty;
                trades.push_back(std::move(t));

                incoming.remaining_qty -= qty;
                maker.remaining_qty -= qty;
                if (maker.remaining_qty == 0)
                    queue.pop_front();
            }
            if (queue.empty()) {
                it = asks_.erase(it);
            } else {
                ++it;
            }
        }
        // if incoming remains, add to bids book
        if (incoming.remaining_qty > 0) {
            bids_[incoming.price_ticks].push_back(incoming);
        }
    } else {
        // Sell side matches against bids: highest price first
        auto it = bids_.rbegin();
        while (incoming.remaining_qty > 0 && it != bids_.rend()) {
            int64_t level_price = it->first;
            if (level_price < incoming.price_ticks)
                break;
            auto& queue = it->second;
            while (!queue.empty() && incoming.remaining_qty > 0) {
                InternalOrder& maker = queue.front();
                int64_t qty = std::min(incoming.remaining_qty, maker.remaining_qty);
                Trade t;
                t.trade_id = "";
                t.maker_order_id = maker.order_id;
                t.taker_order_id = incoming.order_id;
                t.price_ticks = maker.price_ticks;
                t.quantity = qty;
                trades.push_back(std::move(t));

                incoming.remaining_qty -= qty;
                maker.remaining_qty -= qty;
                if (maker.remaining_qty == 0)
                    queue.pop_front();
            }
            if (queue.empty()) {
                auto base_it = std::next(it).base();
                it = std::make_reverse_iterator(bids_.erase(base_it));
            } else {
                ++it;
            }
        }
        if (incoming.remaining_qty > 0) {
            asks_[incoming.price_ticks].push_back(incoming);
        }
    }

    return trades;
}

bool InstrumentOrderBook::CancelOrder(const std::string& order_id) {
    // Deterministic linear scan removal (acceptable for prototype). A production
    // implementation should keep an index from order_id -> (price level, iterator)
    for (auto& p : bids_) {
        auto& dq = p.second;
        for (auto it = dq.begin(); it != dq.end(); ++it) {
            if (it->order_id == order_id) {
                dq.erase(it);
                return true;
            }
        }
    }
    for (auto& p : asks_) {
        auto& dq = p.second;
        for (auto it = dq.begin(); it != dq.end(); ++it) {
            if (it->order_id == order_id) {
                dq.erase(it);
                return true;
            }
        }
    }
    return false;
}

bool InstrumentOrderBook::ModifyOrder(
    const std::string& order_id, int64_t new_price_ticks, int64_t new_qty
) {
    for (auto& p : bids_) {
        auto& dq = p.second;
        for (auto it = dq.begin(); it != dq.end(); ++it) {
            if (it->order_id == order_id) {
                InternalOrder modified = *it;
                dq.erase(it);
                modified.price_ticks = new_price_ticks;
                modified.remaining_qty = new_qty;
                modified.arrival_seq = next_seq_++;
                if (modified.remaining_qty > 0) {
                    bids_[modified.price_ticks].push_back(modified);
                }
                return true;
            }
        }
    }
    for (auto& p : asks_) {
        auto& dq = p.second;
        for (auto it = dq.begin(); it != dq.end(); ++it) {
            if (it->order_id == order_id) {
                InternalOrder modified = *it;
                dq.erase(it);
                modified.price_ticks = new_price_ticks;
                modified.remaining_qty = new_qty;
                modified.arrival_seq = next_seq_++;
                if (modified.remaining_qty > 0) {
                    asks_[modified.price_ticks].push_back(modified);
                }
                return true;
            }
        }
    }
    return false;
}

std::string InstrumentOrderBook::Snapshot() const {
    return std::string();
}

void InstrumentOrderBook::RestoreFromSnapshot(const std::string& blob) {
    (void)blob;
}

}  // namespace velocity
